- sections:
  - title: Getting Started
    link: docs/getting-started.md
    open: true
    sections:
    - title: Setup a tenant
      link: docs/getting-started/setup-tenant/setup-tenant.md
      open: true
      articles:
      - title: Setup tenant
        link: docs/getting-started/setup-tenant/setup-tenant.md
      - title: Deploy tenant
        link: docs/getting-started/setup-tenant/deploy-tenant.md
      - title: Register tenant
        link: docs/getting-started/setup-tenant/register-tenant.md
    - title: Create a tenant
      link: docs/getting-started/create-a-tenant/create-tenant.md
      articles:
      - title: Code tenant
        link: docs/getting-started/code-a-tenant/code-tenant.md
      - title: Deploy tenant
        link: docs/getting-started/setup-tenant/deploy-tenant.md
      - title: Register tenant
        link: docs/getting-started/setup-tenant/register-tenant.md
    - title: Preview & Publish
      link: docs/getting-started/preview-and-publish-content/preview-and-publish.md
- sections:
  - title: Resources
    link:
    open: true
    sections:
    - title: Guides
      link: docs/resources/api-guide.md
      open: true
      articles:
      - title: How it works
        link: docs/resources/guides/how-it-works.md
      - title: How to use Stoplight
        link: docs/resources/guides/using-stoplight.md
      - title: How to use GitLab
        link: docs/resources/guides/using-gitlab.md
      - title: Register tenant
        link: docs/getting-started/setup-tenant/register-tenant.md
      - title: Markdown Support
        link: docs/resources/markdown-support.md
      - title: Tutorials
        link: docs/tutorials/tutorials.md
    - title: FAQ
      link: docs/faq/faq.md